rel to #ISSUE_NUMBER: Disable check-secrets job in tests workflow
Co-authored-by: JakeDot <12250212+JakeDot@users.noreply.github.com>

diff --git a/.github/workflows/tests.yml b/.github/workflows/tests.yml
--- a/.github/workflows/tests.yml
+++ b/.github/workflows/tests.yml
@@ -36,42 +36,42 @@ jobs:
       - name: Check websites status
         uses: ./.github/actions/check-websites
 
-  check-secrets:
-    runs-on: ubuntu-latest
-    steps:
-      - name: Debug concurrency-group
-        run: |
-          # concurrency:
-          #   group: ci-tests-${{ github.event.pull_request.head.label || github.ref }}
-          #   cancel-in-progress: ${{ !((github.ref == 'refs/heads/master' || github.ref == 'refs/heads/release') && github.event_name == 'push') }}
-
-      - name: Debug
-        uses: raven-actions/debug@v1
-
-      - name: Check secrets
-        run: |
-          if [ -z "${{ secrets.KEY_STORE }}" ]; then
-            echo "::error::No secret defined or no access to secrets"
-            exit 1
-          fi
-          echo "::notice::Secrets seems available"
-
-      - name: Get User Permission
-        id: checkAccess
-        uses: actions-cool/check-user-permission@v2
-        with:
-          require: write
-          username: ${{ github.triggering_actor }}
-
-      - name: Check User Permission
-        if: steps.checkAccess.outputs.require-result == 'false' && !contains(github.event.pull_request.labels.*.name, 'ok-to-test') && github.actor != 'dependabot[bot]' && github.actor != 'github-actions[bot]'
-        run: |
-          echo "::error::${{ github.triggering_actor }} does not have permissions on this repo.\nCurrent permission level is ${{ steps.checkAccess.outputs.user-permission }}\nJob originally triggered by ${{ github.actor }}"
-          exit 1
+# Disabled check-secrets job
+#  check-secrets:
+#    runs-on: ubuntu-latest
+#    steps:
+#      - name: Debug concurrency-group
+#        run: |
+#          # concurrency:
+#          #   group: ci-tests-${{ github.event.pull_request.head.label || github.ref }}
+#          #   cancel-in-progress: ${{ !((github.ref == 'refs/heads/master' || github.ref == 'refs/heads/release') && github.event_name == 'push') }}
+#
+#      - name: Debug
+#        uses: raven-actions/debug@v1
+#
+#      - name: Check secrets
+#        run: |
+#          if [ -z "${{ secrets.KEY_STORE }}" ]; then
+#            echo "::error::No secret defined or no access to secrets"
+#            exit 1
+#          fi
+#          echo "::notice::Secrets seems available"
+#
+#      - name: Get User Permission
+#        id: checkAccess
+#        uses: actions-cool/check-user-permission@v2
+#        with:
+#          require: write
+#          username: ${{ github.triggering_actor }}
+#
+#      - name: Check User Permission
+#        if: steps.checkAccess.outputs.require-result == 'false' && !contains(github.event.pull_request.labels.*.name, 'ok-to-test') && github.actor != 'dependabot[bot]' && github.actor != 'github-actions[bot]'
+#        run: |
+#          echo "::error::${{ github.triggering_actor }} does not have permissions on this repo.\nCurrent permission level is ${{ steps.checkAccess.outputs.user-permission }}\nJob originally triggered by ${{ github.actor }}"
+#          exit 1
 
   checkstyle:
     runs-on: ubuntu-latest
-    needs: check-secrets
     steps:
       - name: Checkout the latest code
         uses: actions/checkout@v4
@@ -133,7 +133,6 @@ jobs:
 
   lint:
     runs-on: ubuntu-latest
-    needs: check-secrets
     steps:
       - name: Checkout the latest code
         uses: actions/checkout@v4
@@ -200,7 +199,7 @@ jobs:
     # > are 2-3 times faster than the macOS ones which are also a lot more expensive.
     # https://github.com/ReactiveCircus/android-emulator-runner#running-hardware-accelerated-emulators-on-linux-runners
     runs-on: ubuntu-latest
-    needs: [check-secrets, check-websites]
+    needs: check-websites
     strategy:
       fail-fast: false
       matrix:
